import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')

function readSiteUrl() {
  let fromConfig = ''
  try {
    const config = JSON.parse(readFileSync(resolve(root, 'site.config.json'), 'utf8'))
    fromConfig = config.siteUrl ?? ''
  } catch {
    // site.config.json optional during first clone
  }

  return (process.env.VITE_SITE_URL || process.env.SITE_URL || fromConfig || '').replace(/\/$/, '')
}

const siteUrl = readSiteUrl()
const today = new Date().toISOString().slice(0, 10)

const pages = [
  { path: '/', priority: '1.0', changefreq: 'daily' },
  { path: '/about.html', priority: '0.7', changefreq: 'monthly' },
  { path: '/privacy.html', priority: '0.6', changefreq: 'monthly' },
]

const sitemapEntries = pages
  .map((page) => {
    const loc = siteUrl ? `${siteUrl}${page.path === '/' ? '/' : page.path}` : page.path
    return `  <url>
    <loc>${loc}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${page.changefreq}</changefreq>
    <priority>${page.priority}</priority>
  </url>`
  })
  .join('\n')

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${sitemapEntries}
</urlset>
`

writeFileSync(resolve(root, 'public/sitemap.xml'), sitemap)

const robots = `User-agent: *
Allow: /

Disallow: /data/

Sitemap: ${siteUrl ? `${siteUrl}/sitemap.xml` : '/sitemap.xml'}
`

writeFileSync(resolve(root, 'public/robots.txt'), robots)

mkdirSync(resolve(root, 'src/generated'), { recursive: true })
writeFileSync(
  resolve(root, 'src/generated/siteUrl.ts'),
  `// Auto-generated by scripts/generate-seo.mjs. Do not edit manually.\nexport const SITE_URL = ${JSON.stringify(siteUrl)}\n`,
)

if (!siteUrl) {
  console.warn(
    '[generate-seo] site.config.json의 siteUrl이 비어 있습니다. 배포 도메인을 넣으면 사이트맵·robots가 완전해집니다.',
  )
} else {
  console.log(`[generate-seo] Generated SEO files for ${siteUrl}`)
}
